In [3]:
import pandas as pd

# 1. Read a .csv from a URL with Pandas

Target website: https://www.football-data.co.uk/data.php

In [4]:
# reading 1 csv file from website
df_premier21 = pd.read_csv('https://www.football-data.co.uk/mmz4281/2122/E0.csv')

In [5]:
# showig DataFrame
df_premier21

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,13/08/2021,20:00,Brentford,Arsenal,2,0,H,1,0,...,1.62,0.50,1.75,2.05,1.81,2.13,2.05,2.17,1.80,2.09
1,E0,14/08/2021,12:30,Man United,Leeds,5,1,H,1,0,...,2.25,-1.00,2.05,1.75,2.17,1.77,2.19,1.93,2.10,1.79
2,E0,14/08/2021,15:00,Burnley,Brighton,1,2,A,1,0,...,1.62,0.25,1.79,2.15,1.81,2.14,1.82,2.19,1.79,2.12
3,E0,14/08/2021,15:00,Chelsea,Crystal Palace,3,0,H,2,0,...,1.94,-1.50,2.05,1.75,2.12,1.81,2.16,1.93,2.06,1.82
4,E0,14/08/2021,15:00,Everton,Southampton,3,1,H,0,1,...,1.67,-0.50,2.05,1.88,2.05,1.88,2.08,1.90,2.03,1.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,22/05/2022,16:00,Crystal Palace,Man United,1,0,H,1,0,...,2.04,0.25,1.68,2.15,1.74,2.23,1.88,2.25,1.74,2.16
376,E0,22/05/2022,16:00,Leicester,Southampton,4,1,H,0,0,...,2.63,-0.75,1.83,2.07,1.88,2.03,1.94,2.26,1.87,2.01
377,E0,22/05/2022,16:00,Liverpool,Wolves,3,1,H,1,1,...,3.28,-2.50,2.02,1.77,2.06,1.83,2.19,1.99,2.07,1.80
378,E0,22/05/2022,16:00,Man City,Aston Villa,3,2,H,0,1,...,3.36,-2.25,2.06,1.84,2.05,1.86,2.09,2.03,2.01,1.87
379,E0,22/05/2022,16:00,Norwich,Tottenham,0,5,A,0,2,...,2.40,1.50,1.95,1.95,1.96,1.94,2.16,1.98,1.99,1.89

In [6]:
# rename column
df_premier21.rename(columns = {'FTHG':'home_goals',
                               'FTAG': 'away_goals'}, inplace = True)

In [7]:
# show DataFrame
df_premier21

,Div,Date,Time,HomeTeam,AwayTeam,home_goals,away_goals,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,13/08/2021,20:00,Brentford,Arsenal,2,0,H,1,0,...,1.62,0.50,1.75,2.05,1.81,2.13,2.05,2.17,1.80,2.09
1,E0,14/08/2021,12:30,Man United,Leeds,5,1,H,1,0,...,2.25,-1.00,2.05,1.75,2.17,1.77,2.19,1.93,2.10,1.79
2,E0,14/08/2021,15:00,Burnley,Brighton,1,2,A,1,0,...,1.62,0.25,1.79,2.15,1.81,2.14,1.82,2.19,1.79,2.12
3,E0,14/08/2021,15:00,Chelsea,Crystal Palace,3,0,H,2,0,...,1.94,-1.50,2.05,1.75,2.12,1.81,2.16,1.93,2.06,1.82
4,E0,14/08/2021,15:00,Everton,Southampton,3,1,H,0,1,...,1.67,-0.50,2.05,1.88,2.05,1.88,2.08,1.90,2.03,1.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,22/05/2022,16:00,Crystal Palace,Man United,1,0,H,1,0,...,2.04,0.25,1.68,2.15,1.74,2.23,1.88,2.25,1.74,2.16
376,E0,22/05/2022,16:00,Leicester,Southampton,4,1,H,0,0,...,2.63,-0.75,1.83,2.07,1.88,2.03,1.94,2.26,1.87,2.01
377,E0,22/05/2022,16:00,Liverpool,Wolves,3,1,H,1,1,...,3.28,-2.50,2.02,1.77,2.06,1.83,2.19,1.99,2.07,1.80
378,E0,22/05/2022,16:00,Man City,Aston Villa,3,2,H,0,1,...,3.36,-2.25,2.06,1.84,2.05,1.86,2.09,2.03,2.01,1.87
379,E0,22/05/2022,16:00,Norwich,Tottenham,0,5,A,0,2,...,2.40,1.50,1.95,1.95,1.96,1.94,2.16,1.98,1.99,1.89

# 2. Read .csv from Multiple URLs with Pandas

https://www.football-data.co.uk/mmz4281/2122/E0.csv

Link : root + season + league

In [8]:
# link structure
"https://www.football-data.co.uk/mmz4281/" + "2122" + "/" + "E0" + ".csv"

'https://www.football-data.co.uk/mmz4281/2122/E0.csv'

In [9]:
# create a root variable
root = "https://www.football-data.co.uk/mmz4281/"

## 2.1 Multiple leagues

https://www.football-data.co.uk/mmz4281/2122/E0.csv
https://www.football-data.co.uk/mmz4281/2122/E1.csv
https://www.football-data.co.uk/mmz4281/2122/E2.csv
https://www.football-data.co.uk/mmz4281/2122/E3.csv
https://www.football-data.co.uk/mmz4281/2122/EC.csv

In [10]:
# creating list of league
leagues = ['E0', 'E1', 'E2', 'E3', 'EC']
frames = []
# looping through league, read multiple cvs and append it into a list
for league in leagues:
    df = pd.read_csv(root + '2122' + '/' + league + '.csv', encoding = 'unicode_escape')
    frames.append(df)

In [11]:
# length of frames
len(frames)

5

In [12]:
# show 1st, 2nd and 3rd elements
frames[4]

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,EC,21/08/2021,15:00,Aldershot,Chesterfield,0,2,A,0,0,...,1.93,0.50,1.98,1.83,2.03,1.83,2.05,1.90,1.97,1.80
1,EC,21/08/2021,15:00,Barnet,Notts County,0,5,A,0,0,...,2.06,0.75,1.88,1.93,1.90,1.95,2.00,1.95,1.90,1.88
2,EC,21/08/2021,15:00,Halifax,Maidenhead,1,2,A,1,0,...,1.94,-0.50,1.93,1.88,1.99,1.87,2.03,1.93,1.94,1.84
3,EC,21/08/2021,15:00,Kings Lynn,Southend,0,1,A,0,1,...,1.91,0.25,1.75,2.05,1.81,2.06,1.90,2.11,1.76,2.02
4,EC,21/08/2021,15:00,Solihull,Wrexham,2,2,D,1,2,...,1.85,0.00,2.05,1.75,1.93,1.92,2.05,1.98,1.92,1.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,EC,15/05/2022,15:00,Dover Athletic,Weymouth,1,2,A,0,1,...,2.50,0.25,1.88,1.93,1.87,1.98,1.90,1.98,1.85,1.93
502,EC,15/05/2022,15:00,Eastleigh,Grimsby,4,4,D,0,2,...,2.30,0.50,1.88,1.93,1.88,1.98,1.95,1.98,1.87,1.90
503,EC,15/05/2022,15:00,Maidenhead,Notts County,0,1,A,0,0,...,2.42,0.50,1.95,1.85,2.03,1.83,2.03,1.96,1.92,1.87
504,EC,15/05/2022,15:00,Southend,Torquay,1,1,D,0,1,...,2.01,-0.25,2.02,1.77,2.03,1.83,2.07,1.85,2.00,1.80
505,EC,15/05/2022,15:00,Stockport,Halifax,2,0,H,1,0,...,1.97,-0.75,1.80,2.00,1.79,2.08,1.93,2.08,1.84,1.95

## 2.2 Multiple Seasonns

In [22]:
# creating list of league
leagues = ['E0', 'E2', 'E3']
frames = []

# loop through range of seasons and insert new column
for league in leagues:
    for season in range(15,21):
        df = pd.read_csv(root + str(season) + str(season + 1) + '/' + league + '.csv', encoding = 'unicode_escape')
        df.insert(1, 'season', season)
        frames.append(df)

In [21]:
# total frames (6 seasons x 3 leagues)
len(frames)

18

In [15]:
# show 1st and last elemets (new season column was created)
frames[17]

,Div,season,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E3,20,12/09/2020,15:00,Barrow,Stevenage,1,1,D,1,...,1.76,-0.25,1.95,1.90,1.93,1.98,1.98,1.99,1.91,1.92
1,E3,20,12/09/2020,15:00,Bolton,Forest Green,0,1,A,0,...,1.79,-0.25,2.02,1.83,2.04,1.87,2.09,1.90,2.00,1.83
2,E3,20,12/09/2020,15:00,Bradford,Colchester,0,0,D,0,...,1.65,-0.25,2.07,1.72,2.11,1.82,2.20,1.82,2.09,1.76
3,E3,20,12/09/2020,15:00,Cambridge,Carlisle,3,0,H,2,...,1.70,-0.25,1.98,1.88,2.02,1.88,2.04,1.90,1.99,1.84
4,E3,20,12/09/2020,15:00,Cheltenham,Morecambe,1,2,A,1,...,1.75,-0.50,1.83,2.02,1.87,2.04,1.88,2.09,1.83,2.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,E3,20,08/05/2021,15:00,Port Vale,Mansfield,0,3,A,0,...,1.84,0.25,1.90,1.95,1.89,2.00,1.95,2.07,1.85,1.97
548,E3,20,08/05/2021,15:00,Scunthorpe,Stevenage,0,1,A,0,...,1.73,0.50,1.80,2.05,1.84,2.06,1.87,2.14,1.77,2.07
549,E3,20,08/05/2021,15:00,Southend,Newport County,1,1,D,1,...,1.44,0.50,1.93,1.93,1.94,1.94,1.97,1.97,1.91,1.91
550,E3,20,08/05/2021,15:00,Tranmere,Colchester,0,0,D,0,...,1.59,-0.75,2.05,1.80,2.05,1.85,2.08,1.89,2.01,1.82
551,E3,20,08/05/2021,16:00,Salford,Leyton Orient,3,0,H,1,...,1.87,-1.00,1.98,1.88,1.99,1.90,2.01,1.96,1.96,1.86

# 3. Organize all the data in a Dictionary

In [16]:
# create a dictionary with original name of league as key
dict_countries = {
   'Spanish La Liga':'SP1', 'Spanish Segunda Division':'SP2',
              'German Bundesliga':'D1', 
              'English Premier League':'E0', 'English League 1':'E2', 'English League 2':'E3',
             }

In [23]:
dict_historical_data = {}

# creating list of league
#leagues = ['E0', 'E2', 'E3']

# looping through key elements 
for league in dict_countries:
    frames = []
    for season in range(15, 21):
        df = pd.read_csv(root + str(season) + str(season + 1) + '/' + dict_countries[league] + '.csv', encoding = 'unicode_escape')
        df.insert(1, 'season', season)
        frames.append(df)
    df_concat = pd.concat(frames)
    dict_historical_data[league] = df_concat

In [27]:
# show datframe inside dict_historical_data
dict_historical_data['English Premier League']

,Div,season,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,15,08/08/2015,Bournemouth,Aston Villa,0,1,A,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,E0,15,08/08/2015,Chelsea,Swansea,2,2,D,2,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,E0,15,08/08/2015,Everton,Watford,2,2,D,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,E0,15,08/08/2015,Leicester,Sunderland,4,2,H,3,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,E0,15,08/08/2015,Man United,Tottenham,1,0,H,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,20,23/05/2021,Liverpool,Crystal Palace,2,0,H,1,0,...,3.49,-2.25,1.86,2.04,1.88,2.03,1.98,2.14,1.88,2.00
376,E0,20,23/05/2021,Man City,Everton,5,0,H,2,0,...,2.77,-1.75,2.01,1.89,1.99,1.89,2.20,2.00,2.03,1.85
377,E0,20,23/05/2021,Sheffield United,Burnley,1,0,H,1,0,...,2.05,0.00,2.04,1.86,2.05,1.86,2.17,1.90,2.03,1.84
378,E0,20,23/05/2021,West Ham,Southampton,3,0,H,2,0,...,2.14,-0.75,2.00,1.90,2.02,1.91,2.06,2.01,1.99,1.89
379,E0,20,23/05/2021,Wolves,Man United,1,2,A,1,2,...,1.62,-0.25,2.04,1.86,2.10,1.84,2.10,1.94,2.00,1.88